FROM python:3.12-slim

# 设置工作目录
WORKDIR /opt/application

# 设置用户
USER root

# 安装依赖
RUN apt-get update && apt-get install -y \
    build-essential \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*


# 复制依赖文件
COPY requirements.txt .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

